# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function made with Rcpp
#'
#' @param x a numeric vector
#' @return a number
timesTwo <- function(x) {
    .Call(`_PackageWRcpp_timesTwo`, x)
}

